// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using login.rently.Data;

#nullable disable

namespace login.rently.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316061242_FinalDatabaseSync")]
    partial class FinalDatabaseSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("login.rently.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("login.rently.Models.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("adminid")
                        .HasColumnType("int");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<int>("itemid")
                        .HasColumnType("int");

                    b.Property<int>("lenderid")
                        .HasColumnType("int");

                    b.Property<int>("renterid")
                        .HasColumnType("int");

                    b.Property<DateTime>("startdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.HasIndex("itemid");

                    b.HasIndex("lenderid");

                    b.HasIndex("renterid");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("login.rently.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("adminid")
                        .HasColumnType("int");

                    b.Property<bool>("availability")
                        .HasColumnType("bit");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lenderid")
                        .HasColumnType("int");

                    b.Property<decimal>("priceperday")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.HasIndex("lenderid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("login.rently.Models.Lender", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("adminid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.ToTable("Lenders");
                });

            modelBuilder.Entity("login.rently.Models.Message", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("lenderid")
                        .HasColumnType("int");

                    b.Property<string>("messagetext")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("renterid")
                        .HasColumnType("int");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("lenderid");

                    b.HasIndex("renterid");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("login.rently.Models.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("adminid")
                        .HasColumnType("int");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<int>("renterid")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("transactiondate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.HasIndex("bookingid");

                    b.HasIndex("renterid");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("login.rently.Models.Renter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("adminid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("verified")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.ToTable("Renters");
                });

            modelBuilder.Entity("login.rently.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("bookingid")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("bookingid");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("login.rently.Models.Booking", b =>
                {
                    b.HasOne("login.rently.Models.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Item", "item")
                        .WithMany()
                        .HasForeignKey("itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Lender", "lender")
                        .WithMany()
                        .HasForeignKey("lenderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Renter", "renter")
                        .WithMany()
                        .HasForeignKey("renterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");

                    b.Navigation("item");

                    b.Navigation("lender");

                    b.Navigation("renter");
                });

            modelBuilder.Entity("login.rently.Models.Item", b =>
                {
                    b.HasOne("login.rently.Models.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Lender", "lender")
                        .WithMany()
                        .HasForeignKey("lenderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");

                    b.Navigation("lender");
                });

            modelBuilder.Entity("login.rently.Models.Lender", b =>
                {
                    b.HasOne("login.rently.Models.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("login.rently.Models.Message", b =>
                {
                    b.HasOne("login.rently.Models.Lender", "lender")
                        .WithMany()
                        .HasForeignKey("lenderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Renter", "renter")
                        .WithMany()
                        .HasForeignKey("renterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lender");

                    b.Navigation("renter");
                });

            modelBuilder.Entity("login.rently.Models.Payment", b =>
                {
                    b.HasOne("login.rently.Models.Admin", "admin")
                        .WithMany()
                        .HasForeignKey("adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("login.rently.Models.Renter", "renter")
                        .WithMany()
                        .HasForeignKey("renterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");

                    b.Navigation("booking");

                    b.Navigation("renter");
                });

            modelBuilder.Entity("login.rently.Models.Renter", b =>
                {
                    b.HasOne("login.rently.Models.Admin", "Admins")
                        .WithMany()
                        .HasForeignKey("adminid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admins");
                });

            modelBuilder.Entity("login.rently.Models.Review", b =>
                {
                    b.HasOne("login.rently.Models.Booking", "booking")
                        .WithMany()
                        .HasForeignKey("bookingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("booking");
                });
#pragma warning restore 612, 618
        }
    }
}
